/**
 * @areo/core - Environment Variable Management
 *
 * Type-safe environment variable handling with validation,
 * .env file loading, and runtime access.
 */
/** Supported environment variable types */
export type EnvType = 'string' | 'number' | 'boolean' | 'json' | 'array';
/** Environment variable schema definition */
export interface EnvSchema<T = unknown> {
    type: EnvType;
    required?: boolean;
    default?: T;
    description?: string;
    /** Validation function */
    validate?: (value: T) => boolean | string;
    /** Transform function */
    transform?: (value: string) => T;
    /** Mark as public (exposed to client) */
    public?: boolean;
}
/** Type-safe schema builder */
export interface EnvSchemaBuilder<T> {
    /** Mark as required (no default) */
    required(): EnvSchemaBuilder<T>;
    /** Set default value */
    default(value: T): EnvSchemaBuilder<T>;
    /** Add description */
    description(desc: string): EnvSchemaBuilder<T>;
    /** Add validation */
    validate(fn: (value: T) => boolean | string): EnvSchemaBuilder<T>;
    /** Mark as public (exposed to client) */
    public(): EnvSchemaBuilder<T>;
    /** Get the schema definition */
    _schema: EnvSchema<T>;
}
/** Parsed environment configuration */
export interface ParsedEnv {
    [key: string]: string | number | boolean | unknown[] | Record<string, unknown> | null;
}
/** Environment validation result */
export interface EnvValidationResult {
    valid: boolean;
    errors: EnvValidationError[];
    warnings: string[];
    env: ParsedEnv;
}
/** Environment validation error */
export interface EnvValidationError {
    key: string;
    message: string;
    expected?: string;
    received?: string;
}
/** Environment config for defineConfig */
export interface EnvConfig {
    [key: string]: EnvSchemaBuilder<unknown>;
}
/**
 * Environment variable schema builders.
 * Use these to define your environment variables in areo.config.ts.
 *
 * @example
 * import { env } from '@areo/core';
 *
 * export default defineConfig({
 *   env: {
 *     DATABASE_URL: env.string().required(),
 *     PORT: env.number().default(3000),
 *     DEBUG: env.boolean().default(false),
 *     ALLOWED_ORIGINS: env.array().default([]),
 *   },
 * });
 */
export declare const env: {
    /** String environment variable */
    string(): EnvSchemaBuilder<string>;
    /** Number environment variable */
    number(): EnvSchemaBuilder<number>;
    /** Boolean environment variable */
    boolean(): EnvSchemaBuilder<boolean>;
    /** JSON environment variable (parses as object) */
    json<T = Record<string, unknown>>(): EnvSchemaBuilder<T>;
    /** Array environment variable (comma-separated) */
    array(): EnvSchemaBuilder<string[]>;
    /** Enum environment variable (restricted values) */
    enum<T extends string>(values: readonly T[]): EnvSchemaBuilder<T>;
    /** URL environment variable */
    url(): EnvSchemaBuilder<string>;
    /** Port environment variable (1-65535) */
    port(): EnvSchemaBuilder<number>;
};
/**
 * Parse a .env file content into key-value pairs.
 */
export declare function parseEnvFile(content: string): Record<string, string>;
/**
 * Load environment variables from .env files.
 * Priority (highest to lowest):
 * 1. process.env (already set)
 * 2. .env.local (never committed)
 * 3. .env.[mode].local
 * 4. .env.[mode]
 * 5. .env
 */
export declare function loadEnvFiles(root: string, mode?: 'development' | 'production' | 'test'): Promise<Record<string, string>>;
/**
 * Validate and parse environment variables against a schema.
 */
export declare function validateEnv(schema: EnvConfig, rawEnv: Record<string, string | undefined>): EnvValidationResult;
/**
 * Initialize the environment with validated values.
 * Called during app startup.
 */
export declare function initializeEnv(validatedEnv: ParsedEnv): void;
/**
 * Get an environment variable.
 * Returns undefined if not set (and no default).
 */
export declare function getEnv<T = string>(key: string): T | undefined;
/**
 * Get an environment variable or throw if not set.
 */
export declare function requireEnv<T = string>(key: string): T;
/**
 * Get all environment variables.
 */
export declare function getAllEnv(): Readonly<ParsedEnv>;
/**
 * Get public environment variables (safe for client).
 */
export declare function getPublicEnv(schema: EnvConfig): ParsedEnv;
/**
 * Complete environment initialization.
 * Loads .env files and validates against schema.
 */
export declare function setupEnv(root: string, schema: EnvConfig, mode?: 'development' | 'production' | 'test'): Promise<EnvValidationResult>;
/**
 * Generate TypeScript type definitions for environment variables.
 */
export declare function generateEnvTypes(schema: EnvConfig): string;
/**
 * Module augmentation target for environment types.
 * Generated by the CLI during development.
 */
export interface EnvTypes {
}
/**
 * Type-safe environment variable accessor.
 * Use after defining env schema in areo.config.ts.
 *
 * @example
 * const dbUrl = typedEnv.DATABASE_URL; // TypeScript knows this is string
 */
export declare const typedEnv: EnvTypes;
//# sourceMappingURL=env.d.ts.map