/**
 * @ereo/client-sdk - Type definitions for API routes
 *
 * These types support end-to-end type safety for API calls.
 * Routes declare their API types, and the client SDK uses them.
 */

// ============================================================================
// HTTP Methods
// ============================================================================

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

// ============================================================================
// API Route Type Registry
// ============================================================================

/**
 * Module augmentation target for API route types.
 * Generated by the bundler during development.
 *
 * @example
 * declare module '@ereo/client-sdk' {
 *   interface ApiRoutes {
 *     '/api/posts': {
 *       GET: {
 *         response: Post[];
 *         query?: { limit?: number; offset?: number };
 *       };
 *       POST: {
 *         body: CreatePostInput;
 *         response: Post;
 *       };
 *     };
 *   }
 * }
 */
export interface ApiRoutes {}

/** All registered API route paths */
export type ApiPaths = keyof ApiRoutes extends never ? string : keyof ApiRoutes;

// ============================================================================
// Type Extraction Helpers
// ============================================================================

/** Get all supported methods for a path */
export type MethodsFor<Path extends ApiPaths> = Path extends keyof ApiRoutes
  ? keyof ApiRoutes[Path] extends HttpMethod
    ? keyof ApiRoutes[Path]
    : never
  : HttpMethod;

/** Get request body type for a path and method */
export type RequestBody<
  Path extends ApiPaths,
  Method extends HttpMethod = 'POST'
> = Path extends keyof ApiRoutes
  ? Method extends keyof ApiRoutes[Path]
    ? ApiRoutes[Path][Method] extends { body: infer B }
      ? B
      : never
    : never
  : unknown;

/** Get response type for a path and method */
export type ResponseType<
  Path extends ApiPaths,
  Method extends HttpMethod = 'GET'
> = Path extends keyof ApiRoutes
  ? Method extends keyof ApiRoutes[Path]
    ? ApiRoutes[Path][Method] extends { response: infer R }
      ? R
      : unknown
    : unknown
  : unknown;

/** Get query parameters type for a path and method */
export type QueryParams<
  Path extends ApiPaths,
  Method extends HttpMethod = 'GET'
> = Path extends keyof ApiRoutes
  ? Method extends keyof ApiRoutes[Path]
    ? ApiRoutes[Path][Method] extends { query: infer Q }
      ? Q
      : never
    : never
  : Record<string, string | number | boolean | undefined>;

/** Get path parameters type for a path */
export type PathParams<Path extends string> = Path extends `${infer _}/[${infer Param}]${infer Rest}`
  ? { [K in Param]: string } & PathParams<Rest>
  : Path extends `[${infer Param}]${infer Rest}`
  ? { [K in Param]: string } & PathParams<Rest>
  : Record<string, never>;

// ============================================================================
// Request/Response Types
// ============================================================================

export interface ApiRequestConfig<
  Path extends ApiPaths = ApiPaths,
  Method extends HttpMethod = HttpMethod
> {
  /** Request path */
  path: Path;
  /** HTTP method */
  method: Method;
  /** Path parameters (for dynamic routes) */
  params?: PathParams<Path extends string ? Path : string>;
  /** Query parameters */
  query?: QueryParams<Path, Method>;
  /** Request body */
  body?: RequestBody<Path, Method>;
  /** Request headers */
  headers?: Record<string, string>;
  /** Abort signal */
  signal?: AbortSignal;
}

export interface ApiResponse<T = unknown> {
  /** Response data */
  data: T;
  /** HTTP status code */
  status: number;
  /** Response headers */
  headers: Headers;
  /** Whether response was successful */
  ok: boolean;
}

export interface ApiError extends Error {
  /** HTTP status code */
  status: number;
  /** Response data (if any) */
  data?: unknown;
  /** Request path */
  path: string;
  /** Request method */
  method: string;
}

// ============================================================================
// Client Configuration
// ============================================================================

export interface ClientConfig {
  /** Base URL for API requests */
  baseUrl?: string;
  /** Default headers */
  headers?: Record<string, string>;
  /** Request timeout (ms) */
  timeout?: number;
  /** Enable request/response logging */
  debug?: boolean;
  /** Custom fetch implementation */
  fetch?: typeof fetch;
  /** Request interceptor */
  onRequest?: (config: ApiRequestConfig) => ApiRequestConfig | Promise<ApiRequestConfig>;
  /** Response interceptor */
  onResponse?: <T>(response: ApiResponse<T>) => ApiResponse<T> | Promise<ApiResponse<T>>;
  /** Error handler */
  onError?: (error: ApiError) => void | Promise<void>;
}

// ============================================================================
// Route-Specific API Types Helper
// ============================================================================

/**
 * Helper to define API types for a route module.
 * Use this to declare types that will be picked up by the client SDK.
 *
 * @example
 * // In app/routes/api/posts.ts
 * export interface ApiTypes {
 *   GET: {
 *     response: Post[];
 *     query: { limit?: number };
 *   };
 *   POST: {
 *     body: CreatePostInput;
 *     response: Post;
 *   };
 * }
 */
export type DefineApiTypes<T extends Record<HttpMethod, { response: unknown }>> = T;
